package io.github.hpkaiq.dorisjdbc;

import java.sql.*;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class DorisStatement implements Statement {
    private static final Pattern SHOW_CREATE_AS_TABLE_OR_VIEW_PATTERN = Pattern.compile(
            "^\\s*SHOW\\s+CREATE\\s+(?:TABLE|VIEW)\\s+(.+?)(?:\\s*;\\s*)?$",
            Pattern.CASE_INSENSITIVE | Pattern.DOTALL
    );
    private static final String ASYNC_MATERIALIZED_VIEW_ERROR = "not support async materialized view";

    private final Statement delegate;
    private final DorisConnection conn;

    public DorisStatement(Statement delegate, DorisConnection conn) {
        this.delegate = delegate;
        this.conn = conn;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        String normalizedSql = normalizeSql("executeQuery", sql);
        try {
            return delegate.executeQuery(normalizedSql);
        } catch (SQLException e) {
            String materializedViewSql = rewriteShowCreateViewForAsyncMaterializedView(normalizedSql, e);
            if (materializedViewSql == null) {
                DorisTraceLogger.logError("DorisStatement", "executeQuery | sql=" + normalizedSql, e);
                throw e;
            }
            DorisTraceLogger.logSql("DorisStatement", "executeQuery fallback", materializedViewSql);
            try {
                return delegate.executeQuery(materializedViewSql);
            } catch (SQLException fallbackFailure) {
                fallbackFailure.addSuppressed(e);
                throw fallbackFailure;
            }
        }
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        String normalizedSql = normalizeSql("execute", sql);
        try {
            return delegate.execute(normalizedSql);
        } catch (SQLException e) {
            String materializedViewSql = rewriteShowCreateViewForAsyncMaterializedView(normalizedSql, e);
            if (materializedViewSql == null) {
                DorisTraceLogger.logError("DorisStatement", "execute | sql=" + normalizedSql, e);
                throw e;
            }
            DorisTraceLogger.logSql("DorisStatement", "execute fallback", materializedViewSql);
            try {
                return delegate.execute(materializedViewSql);
            } catch (SQLException fallbackFailure) {
                fallbackFailure.addSuppressed(e);
                throw fallbackFailure;
            }
        }
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        return delegate.getResultSet();
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return delegate.getUpdateCount();
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return delegate.getMoreResults();
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        delegate.setFetchDirection(direction);
    }

    @Override
    public int getFetchDirection() throws SQLException {
        return delegate.getFetchDirection();
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        delegate.setFetchSize(rows);
    }

    @Override
    public int getFetchSize() throws SQLException {
        return delegate.getFetchSize();
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        return delegate.getResultSetConcurrency();
    }

    @Override
    public int getResultSetType() throws SQLException {
        return delegate.getResultSetType();
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        delegate.addBatch(normalizeSql("addBatch", sql));
    }

    @Override
    public void clearBatch() throws SQLException {
        delegate.clearBatch();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        return delegate.executeBatch();
    }

    @Override
    public Connection getConnection() throws SQLException {
        return conn;
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        return delegate.getMoreResults(current);
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return delegate.getGeneratedKeys();
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        int count = delegate.executeUpdate(normalizeSql("executeUpdate", sql), autoGeneratedKeys);
        return count == 0 ? 1 : count;
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        int count = delegate.executeUpdate(normalizeSql("executeUpdate", sql), columnIndexes);
        return count == 0 ? 1 : count;
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        int count = delegate.executeUpdate(normalizeSql("executeUpdate", sql), columnNames);
        return count == 0 ? 1 : count;
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return delegate.execute(normalizeSql("execute", sql), autoGeneratedKeys);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return delegate.execute(normalizeSql("execute", sql), columnIndexes);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return delegate.execute(normalizeSql("execute", sql), columnNames);
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        return delegate.getResultSetHoldability();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return delegate.isClosed();
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        delegate.setPoolable(poolable);
    }

    @Override
    public boolean isPoolable() throws SQLException {
        return delegate.isPoolable();
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        delegate.closeOnCompletion();
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        return delegate.isCloseOnCompletion();
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        int count = delegate.executeUpdate(normalizeSql("executeUpdate", sql));
        return count == 0 ? 1 : count;
    }

    // 其余方法代理
    @Override public void close() throws SQLException { delegate.close(); }
    @Override public int getMaxFieldSize() throws SQLException { return delegate.getMaxFieldSize(); }
    @Override public void setMaxFieldSize(int max) throws SQLException { delegate.setMaxFieldSize(max); }
    @Override public int getMaxRows() throws SQLException { return delegate.getMaxRows(); }
    @Override public void setMaxRows(int max) throws SQLException { delegate.setMaxRows(max); }
    @Override public void setEscapeProcessing(boolean enable) throws SQLException { delegate.setEscapeProcessing(enable); }
    @Override public int getQueryTimeout() throws SQLException { return delegate.getQueryTimeout(); }
    @Override public void setQueryTimeout(int seconds) throws SQLException { delegate.setQueryTimeout(seconds); }
    @Override public void cancel() throws SQLException { delegate.cancel(); }
    @Override public SQLWarning getWarnings() throws SQLException { return delegate.getWarnings(); }
    @Override public void clearWarnings() throws SQLException { delegate.clearWarnings(); }

    @Override
    public void setCursorName(String name) throws SQLException {
        delegate.setCursorName(name);
    }

    @Override public <T> T unwrap(Class<T> iface) throws SQLException { return delegate.unwrap(iface); }
    @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return delegate.isWrapperFor(iface); }

    private static String rewriteShowCreateViewForAsyncMaterializedView(String sql, SQLException e) {
        if (sql == null || e == null || e.getMessage() == null) {
            return null;
        }
        if (!e.getMessage().toLowerCase(Locale.ROOT).contains(ASYNC_MATERIALIZED_VIEW_ERROR)) {
            return null;
        }
        Matcher matcher = SHOW_CREATE_AS_TABLE_OR_VIEW_PATTERN.matcher(sql);
        if (!matcher.matches()) {
            return null;
        }
        return "SHOW CREATE MATERIALIZED VIEW " + matcher.group(1).trim();
    }

    protected static String normalizeSql(String operation, String sql) {
        String normalized = DorisSqlNormalizer.normalize(sql);
        if (normalized != sql) {
            DorisTraceLogger.logSql("DorisStatement", operation + " normalized", normalized);
        }
        return normalized;
    }
}
